version: '3.8'  # Specify the version of Docker Compose

services:
  web:
    image: python:3.13.2-alpine3.21  # Use the specified Python image
    volumes:
      - ./app:/app  # Mount the local app directory to /app in the container
    working_dir: /app  # Set the working directory
    ports:
      - "5000:5000"  # Expose port 5000
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && 
              gunicorn -w 5 --threads 100 -b :8000 'app:create_app()'"
